# Gitpod configuration for CodeSphere IDE

# Use a standard workspace image
image: gitpod/workspace-full:latest

# Tasks to run on workspace start
tasks:
  - name: Install & Build
    init: |
      # Enable Corepack for Yarn 4
      corepack enable

      # Install dependencies
      echo "📦 Installing dependencies..."
      yarn install

      # Build extensions
      echo "🔨 Building extensions..."
      yarn build:extensions

      # Build browser application
      echo "🌐 Building browser application..."
      cd applications/browser && yarn build
      cd ../..

      # Download plugins
      echo "🔌 Downloading plugins..."
      yarn download:plugins || true

      echo "✅ Build complete!"
    command: |
      # Start the application
      echo "🚀 Starting CodeSphere IDE..."
      cd applications/browser
      yarn start --hostname=0.0.0.0 --port=3000

# Ports to expose
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
    description: CodeSphere IDE

# VS Code extensions to install (optional)
vscode:
  extensions:
    - dbaeumer.vscode-eslint

# GitHub prebuilds for faster workspace startup
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
